version: '3.5'

services:
  postgres:
    container_name: gostack_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - "5432:5432"
    restart: unless-stopped

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
